using System.Collections.Generic;

namespace FitReader
{
    internal static class Fields
    {
        private static Dictionary<ushort, Dictionary<ushort, Field>> fields = new Dictionary<ushort, Dictionary<ushort, Field>>()
        {
            { 0, new Dictionary<ushort, Field>()
                {
                    { 0, new Field("filetype", "enumFile", 0, 0) },
                    { 1, new Field("manufacturer", "enumManufacturer", 0, 0) },
                    { 2, new Field("garminProduct", "raw", 0, 0) },
                    { 3, new Field("serialNumber", "raw", 0, 0) },
                    { 4, new Field("timeCreated", "dateTime", 0, 0) },
                    { 5, new Field("number", "raw", 0, 0) },
                    { 8, new Field("productName", "raw", 0, 0) }
                }
            },
            { 2, new Dictionary<ushort, Field>()
                {
                    { 0, new Field("activityTimeZone", "unit8", 0, 0) },
                    { 1, new Field("utcOffset", "unit32", 0, 0) },
                    { 2, new Field("timeOffset", "unit32", 0, 0) },
                    { 4, new Field("timeMode", "enumTimeMode", 0, 0) },
                    { 5, new Field("timeZoneOffset", "sint8", 4, 0) },
                    { 36, new Field("backlightMode", "enumBacklightMode", 0, 0) },
                    { 39, new Field("clockTime", "dateTime", 0, 0) },
                    { 40, new Field("pagesEnabled", "uint16", 0, 0) },
                    { 46, new Field("moveAlertEnabled", "bool", 0, 0) },
                    { 47, new Field("dateMode", "enumDateMode", 0, 0) },
                    { 55, new Field("displayOrientation", "enumDisplayOrientation", 0, 0) },
                    { 56, new Field("mountingSide", "enumSide", 0, 0) },
                    { 57, new Field("defaultPage", "uint16", 0, 0) },
                    { 58, new Field("autosyncMinSteps", "uint16", 0, 0) },
                    { 59, new Field("autoSyncMinTime", "uint16", 0, 0) },
                    { 80, new Field("lactateThresholdAutodetectEnabled", "bool", 0, 0) },
                    { 86, new Field("bleAutoUploadEnabled", "bool", 0, 0) },
                    { 89, new Field("autoSyncFrequency", "enumAutoSyncFrequency", 0, 0) },
                    { 90, new Field("autoActivityDetect", "uint32", 0, 0) },
                    { 94, new Field("numberOfScreens", "uint8", 0, 0) },
                    { 95, new Field("smartNotificationDisplayOrientation", "enumDisplayOrientation", 0, 0) },
                    { 134, new Field("tapInterface", "enumSwitch", 0, 0) }
              }
            },
            { 3, new Dictionary<ushort, Field>()
              {
                { 254, new Field("messageIndex", "messageIndex", 0, 0) },
                { 0, new Field("friendlyName", "string", 0, 0) },
                { 1, new Field("gender", "enumGender", 0, 0) },
                { 2, new Field("age", "raw", 0, 0) },
                { 3, new Field("height", "uint8", 100, 0) },
                { 4, new Field("weight", "uint16", 10, 0) },
                { 5, new Field("language", "enumLanguage", 0, 0) },
                { 6, new Field("elevSetting", "enumDisplayMeasure", 0, 0) },
                { 7, new Field("weightSetting", "enumDisplayMeasure", 0, 0) },
                { 8, new Field("restingHeartRate", "uint8", 0, 0) },
                { 9, new Field("defaultMaxRunningHeartRate", "uint8", 0, 0) },
                { 10, new Field("defaultMaxBikingHeartRate", "uint8", 0, 0) },
                { 11, new Field("defaultMaxHeartRate", "uint8", 0, 0) },
                { 12, new Field("hrSetting", "enumDisplayHeart", 0, 0) },
                { 13, new Field("speedSetting", "enumDisplayMeasure", 0, 0) },
                { 14, new Field("distSetting", "enumDisplayMeasure", 0, 0) },
                { 16, new Field("powerSetting", "enumDisplayPower", 0, 0) },
                { 17, new Field("activityClass", "enumActivityClass", 0, 0) },
                { 18, new Field("positionSetting", "enumDisplayPosition", 0, 0) },
                { 21, new Field("temperatureSetting", "enumDisplayMeasure", 0, 0) },
                { 22, new Field("localId", "userLocalId", 0, 0) },
                { 23, new Field("globalId", "byte", 0, 0) },
                { 30, new Field("heightSetting", "enumDisplayMeasure", 0, 0) }
              }
            },
            { 6, new Dictionary<ushort, Field>()
              {
                { 254, new Field("messageIndex", "messageIndex", 0, 0) },
                { 0, new Field("name", "string", 0, 0) },
                { 1, new Field("sport", "enumSport", 0, 0) },
                { 2, new Field("subSport", "enumSubSport", 0, 0) },
                { 3, new Field("odometer", "uint32", 100, 0) },
                { 4, new Field("bikeSpdAntId", "uint16z", 0, 0) },
                { 5, new Field("bikeCadAntId", "uint16z", 0, 0) },
                { 6, new Field("bikeSpdcadAntId", "uint16z", 0, 0) },
                { 7, new Field("bikePowerAntId", "uint16z", 0, 0) },
                { 8, new Field("customWheelsize", "uint16", 1000, 0) },
                { 9, new Field("autoWheelsize", "uint16", 1000, 0) },
                { 10, new Field("bikeWeight", "uint16", 10, 0) },
                { 11, new Field("powerCalFactor", "uint16", 10, 0) },
                { 12, new Field("autoWheelCal", "bool", 0, 0) },
                { 13, new Field("autoPowerZero", "bool", 0, 0) },
                { 14, new Field("id", "uint8", 0, 0) },
                { 15, new Field("spdEnabled", "bool", 0, 0) },
                { 16, new Field("cadEnabled", "bool", 0, 0) },
                { 17, new Field("spdcadEnabled", "bool", 0, 0) },
                { 18, new Field("powerEnabled", "bool", 0, 0) },
                { 19, new Field("crankLength", "uint8", 2, 0) },
                { 20, new Field("enabled", "bool", 0, 0) },
                { 21, new Field("bikeSpdAntIdTransType", "uint8z", 0, 0) },
                { 22, new Field("bikeCadAntIdTransType", "uint8z", 0, 0) },
                { 23, new Field("bikeSpdcadAntIdTransType", "uint8z", 0, 0) },
                { 24, new Field("bikePowerAntIdTransType", "uint8z", 0, 0) }
              }
            },
            { 7, new Dictionary<ushort, Field>()
              {
                { 1, new Field("maxHeartRate", "uint8", 0, 0) },
                { 2, new Field("thresholdHeartRate", "uint8", 0, 0) },
                { 3, new Field("functionalThresholdPower", "uint16", 0, 0) },
                { 5, new Field("hrCalcType", "hrZoneCalc", 0, 0) },
                { 7, new Field("pwrCalcType", "pwrZoneCalc", 0, 0) },
              }
            },
            { 18, new Dictionary<ushort, Field>()
              {
                { 254, new Field("messageIndex", "messageIndex", 0, 0) },
                { 253, new Field("timestamp", "dateTime", 0, 0) },
                { 0, new Field("event", "enumEvent", 0, 0) },
                { 1, new Field("eventType", "enumEventType", 0, 0) },
                { 2, new Field("startTime", "dateTime", 0, 0) },
                { 3, new Field("startPositionLat", "coordinates", 0, 0) },
                { 4, new Field("startPositionLong", "coordinates", 0, 0) },
                { 5, new Field("sport", "enumSport", 0, 0) },
                { 6, new Field("subSport", "enumSubSport", 0, 0) },
                { 7, new Field("totalElapsedTime", "uint32", 1000, 0) },
                { 8, new Field("totalTimerTime", "uint32", 1000, 0) },
                { 9, new Field("totalDistance", "uint32", 100, 0) },
                { 10, new Field("totalCycles", "uint32", 0, 0) },
                { 11, new Field("totalCalories", "uint16", 0, 0) },
                { 13, new Field("totalFatCalories", "uint16", 0, 0) },
                { 14, new Field("avgSpeed", "uint16", 1000, 0) },
                { 15, new Field("maxSpeed", "uint16", 1000, 0) },
                { 16, new Field("avgHeartRate", "uint8", 0, 0) },
                { 17, new Field("maxHeartRate", "uint8", 0, 0) },
                { 18, new Field("avgCadence", "uint8", 0, 0) },
                { 19, new Field("maxCadence", "uint8", 0, 0) },
                { 20, new Field("avgPower", "uint16", 0, 0) },
                { 21, new Field("maxPower", "uint16", 0, 0) },
                { 22, new Field("totalAscent", "uint16", 0, 0) },
                { 23, new Field("totalDescent", "uint16", 0, 0) },
                { 24, new Field("totalTrainingEffect", "uint8", 10, 0) },
                { 25, new Field("firstLapIndex", "uint16", 0, 0) },
                { 26, new Field("numLaps", "uint16", 0, 0) },
                { 27, new Field("eventGroup", "uint8", 0, 0) },
                { 28, new Field("trigger", "enumSessionTrigger", 0, 0) },
                { 29, new Field("necLat", "coordinates", 0, 0) },
                { 30, new Field("necLong", "coordinates", 0, 0) },
                { 31, new Field("swcLat", "coordinates", 0, 0) },
                { 32, new Field("swcLong", "coordinates", 0, 0) },
                { 34, new Field("normalizedPower", "uint16", 0, 0) },
                { 35, new Field("trainingStressScore", "uint16", 10, 0) },
                { 36, new Field("intensityFactor", "uint16", 1000, 0) },
                { 37, new Field("leftRightBalance", "leftRightBalance100", 0, 0) },
                { 41, new Field("avgStrokeCount", "uint32", 10, 0) },
                { 42, new Field("avgStrokeDistance", "uint16", 100, 0) },
                { 44, new Field("poolLength", "uint16", 100, 0) },
                { 45, new Field("thresholdPower", "uint16", 0, 0) },
                { 46, new Field("poolLengthUnit", "enumDisplayMeasure", 0, 0) },
                { 47, new Field("numActiveLengths", "uint16", 0, 0) },
                { 48, new Field("totalWork", "uint32", 0, 0) },
                { 49, new Field("avgAltitude", "uint16", 5, 0) },
                { 50, new Field("maxAltitude", "uint16", 5, 0) },
                { 51, new Field("gpsAccuracy", "uint8", 0, 0) },
                { 52, new Field("avgGrade", "sint16", 100, 0) },
                { 53, new Field("avgPosGrade", "sint16", 100, 0) },
                { 54, new Field("avgNegGrade", "sint16", 100, 0) },
                { 55, new Field("maxPosGrade", "sint16", 100, 0) },
                { 56, new Field("maxNegGrade", "sint16", 100, 0) },
                { 57, new Field("avgTemperature", "sint8", 0, 0) },
                { 58, new Field("maxTemperature", "sint8", 0, 0) },
                { 59, new Field("totalMovingTime", "uint32", 1000, 0) },
                { 60, new Field("avgPosVerticalSpeed", "sint16", 1000, 0) },
                { 61, new Field("avgNegVerticalSpeed", "sint16", 1000, 0) },
                { 62, new Field("maxPosVerticalSpeed", "sint16", 1000, 0) },
                { 63, new Field("maxNegVerticalSpeed", "sint16", 1000, 0) },
                { 64, new Field("minHeartRate", "uint8", 0, 0) },
                { 65, new Field("timeInHrZone", "uint32", 1000, 0) },
                { 66, new Field("timeInSpeedZone", "uint32", 1000, 0) },
                { 67, new Field("timeInCadenceZone", "uint32", 1000, 0) },
                { 68, new Field("timeInPowerZone", "uint32", 1000, 0) },
                { 69, new Field("avgLapTime", "uint32", 1000, 0) },
                { 70, new Field("bestLapIndex", "uint16", 0, 0) },
                { 71, new Field("minAltitude", "uint16", 5, 500) },
                { 82, new Field("playerScore", "uint16", 0, 0) },
                { 83, new Field("opponentScore", "uint16", 0, 0) },
                { 84, new Field("opponentName", "string", 0, 0) },
                { 85, new Field("strokeCount", "uint16", 0, 0) },
                { 86, new Field("zoneCount", "uint16", 0, 0) },
                { 87, new Field("maxBallSpeed", "uint16", 100, 0) },
                { 88, new Field("avgBallSpeed", "uint16", 100, 0) },
                { 89, new Field("avgVerticalOscillation", "uint16", 10, 0) },
                { 90, new Field("avgStanceTimePercent", "uint16", 100, 0) },
                { 91, new Field("avgStanceTime", "uint16", 10, 0) },
                { 92, new Field("avgFractionalCadence", "uint8", 128, 0) },
                { 93, new Field("maxFractionalCadence", "uint8", 128, 0) },
                { 94, new Field("totalFractionalCycles", "uint8", 128, 0) },
                { 95, new Field("avgTotalHemoglobinConc", "uint16", 100, 0) },
                { 96, new Field("minTotalHemoglobinConc", "uint16", 100, 0) },
                { 97, new Field("maxTotalHemoglobinConc", "uint16", 100, 0) },
                { 98, new Field("avgSaturatedHemoglobinPercent", "uint16", 10, 0) },
                { 99, new Field("minSaturatedHemoglobinPercent", "uint16", 10, 0) },
                { 100, new Field("maxSaturatedHemoglobinPercent", "uint16", 10, 0) },
                { 101, new Field("avgLeftTorqueEffectiveness", "uint8", 2, 0) },
                { 102, new Field("avgRightTorqueEffectiveness", "uint8", 2, 0) },
                { 103, new Field("avgLeftPedalSmoothness", "uint8", 2, 0) },
                { 104, new Field("avgRightPedalSmoothness", "uint8", 2, 0) },
                { 105, new Field("avgCombinedPedalSmoothness", "uint8", 2, 0) },
                { 107, new Field("numFrontGearChanges", "uint16", 0, 0) },
                { 108, new Field("numRearGearChanges", "uint16", 0, 0) },
                { 111, new Field("sportIndex", "uint8", 0, 0) },
                { 112, new Field("timeStanding", "uint32", 1000, 0) },
                { 113, new Field("standCount", "uint16", 0, 0) },
                { 114, new Field("avgLeftPco", "sint8", 0, 0) },
                { 115, new Field("avgRightPco", "sint8", 0, 0) },
                { 116, new Field("avgLeftPowerPhase", "uint8", 0.7111111, 0) },
                { 117, new Field("avgLeftPowerPhasePeak", "uint8", 0.7111111, 0) },
                { 118, new Field("avgRightPowerPhase", "uint8", 0.7111111, 0) },
                { 119, new Field("avgRightPowerPhasePeak", "uint8", 0.7111111, 0) },
                { 120, new Field("avgPowerPosition", "uint16", 0, 0) },
                { 121, new Field("maxPowerPosition", "uint16", 0, 0) },
                { 122, new Field("avgCadencePosition", "uint8", 0, 0) },
                { 123, new Field("maxCadencePosition", "uint8", 0, 0) },
                { 124, new Field("enhancedAvgSpeed", "uint32", 1000, 0) },
                { 125, new Field("enhancedMaxSpeed", "uint32", 1000, 0) },
                { 126, new Field("enhancedAvgAltitude", "uint32", 5, 500) },
                { 127, new Field("enhancedMinAltitude", "uint32", 5, 500) },
                { 128, new Field("enhancedMaxAltitude", "uint32", 5, 500) },
                { 129, new Field("avgLevMotorPower", "uint16", 0, 0) },
                { 130, new Field("maxLevMotorPower", "uint16", 0, 0) },
                { 131, new Field("levBatteryConsumption", "uint8", 2, 0) }
              }
            },
            { 19, new Dictionary<ushort, Field>()
              {
                { 254, new Field("messageIndex", "messageIndex", 0, 0) },
                { 253, new Field("timestamp", "dateTime", 0, 0) },
                { 0, new Field("event", "enumEvent", 0, 0) },
                { 1, new Field("eventType", "enumEventType", 0, 0) },
                { 2, new Field("startTime", "dateTime", 0, 0) },
                { 3, new Field("startPositionLat", "coordinates", 0, 0) },
                { 4, new Field("startPositionLong", "coordinates", 0, 0) },
                { 5, new Field("endPositionLat", "coordinates", 0, 0) },
                { 6, new Field("endPositionLong", "coordinates", 0, 0) },
                { 7, new Field("totalElapsedTime", "uint32", 1000, 0) },
                { 8, new Field("totalTimerTime", "uint32", 1000, 0) },
                { 9, new Field("totalDistance", "uint32", 100, 0) },
                { 10, new Field("totalCycles", "uint32", 0, 0) },
                { 11, new Field("totalCalories", "uint16", 0, 0) },
                { 12, new Field("totalFatCalories", "uint16", 0, 0) },
                { 13, new Field("avgSpeed", "uint16", 1000, 0) },
                { 14, new Field("maxSpeed", "uint16", 1000, 0) },
                { 15, new Field("avgHeartRate", "uint8", 0, 0) },
                { 16, new Field("maxHeartRate", "uint8", 0, 0) },
                { 17, new Field("avgCadence", "uint8", 0, 0) },
                { 18, new Field("maxCadence", "uint8", 0, 0) },
                { 19, new Field("avgPower", "uint16", 0, 0) },
                { 20, new Field("maxPower", "uint16", 0, 0) },
                { 21, new Field("totalAscent", "uint16", 0, 0) },
                { 22, new Field("totalDescent", "uint16", 0, 0) },
                { 23, new Field("intensity", "enumIntensity", 0, 0) },
                { 24, new Field("lapTrigger", "enumLapTrigger", 0, 0) },
                { 25, new Field("sport", "enumSport", 0, 0) },
                { 26, new Field("eventGroup", "uint8", 0, 0) },
                { 27, new Field("necLat", "coordinates", 0, 0) },
                { 28, new Field("necLong", "coordinates", 0, 0) },
                { 29, new Field("swcLat", "coordinates", 0, 0) },
                { 30, new Field("swcLong", "coordinates", 0, 0) },
                { 32, new Field("numLengths", "uint16", 0, 0) },
                { 33, new Field("normalizedPower", "uint16", 0, 0) },
                { 34, new Field("leftRightBalance", "leftRightBalance100", 0, 0) },
                { 35, new Field("firstLengthIndex", "uint16", 0, 0) },
                { 37, new Field("avgStrokeDistance", "uint16", 100, 0) },
                { 38, new Field("swimStroke", "enumSwimStroke", 0, 0) },
                { 39, new Field("subSport", "enumSubSport", 0, 0) },
                { 40, new Field("numActiveLengths", "uint16", 0, 0) },
                { 41, new Field("totalWork", "uint32", 0, 0) },
                { 42, new Field("avgAltitude", "uint16", 5, 500) },
                { 43, new Field("maxAltitude", "uint16", 5, 500) },
                { 44, new Field("gpsAccuracy", "uint8", 0, 0) },
                { 45, new Field("avgGrade", "sint16", 100, 0) },
                { 46, new Field("avgPosGrade", "sint16", 100, 0) },
                { 47, new Field("avgNegGrade", "sint16", 100, 0) },
                { 48, new Field("maxPosGrade", "sint16", 100, 0) },
                { 49, new Field("maxNegGrade", "sint16", 100, 0) },
                { 50, new Field("avgTemperature", "sint8", 0, 0) },
                { 51, new Field("maxTemperature", "sint8", 0, 0) },
                { 52, new Field("totalMovingTime", "uint32", 1000, 0) },
                { 53, new Field("avgPosVerticalSpeed", "sint16", 1000, 0) },
                { 54, new Field("avgNegVerticalSpeed", "sint16", 1000, 0) },
                { 55, new Field("maxPosVerticalSpeed", "sint16", 1000, 0) },
                { 56, new Field("maxNegVerticalSpeed", "sint16", 1000, 0) },
                { 57, new Field("timeInHrZone", "uint32", 1000, 0) },
                { 58, new Field("timeInSpeedZone", "uint32", 1000, 0) },
                { 59, new Field("timeInCadenceZone", "uint32", 1000, 0) },
                { 60, new Field("timeInPowerZone", "uint32", 1000, 0) },
                { 61, new Field("repetitionNum", "uint16", 0, 0) },
                { 62, new Field("minAltitude", "uint16", 5, 500) },
                { 63, new Field("minHeartRate", "uint8", 0, 0) },
                { 71, new Field("wktStepIndex", "messageIndex", 0, 0) },
                { 74, new Field("opponentScore", "uint16", 0, 0) },
                { 75, new Field("strokeCount", "uint16", 0, 0) },
                { 76, new Field("zoneCount", "uint16", 0, 0) },
                { 77, new Field("avgVerticalOscillation", "uint16", 10, 0) },
                { 78, new Field("avgStanceTimePercent", "uint16", 100, 0) },
                { 79, new Field("avgStanceTime", "uint16", 10, 0) },
                { 80, new Field("avgFractionalCadence", "uint8", 128, 0) },
                { 81, new Field("maxFractionalCadence", "uint8", 128, 0) },
                { 82, new Field("totalFractionalCycles", "uint8", 128, 0) },
                { 83, new Field("playerScore", "uint16", 0, 0) },
                { 84, new Field("avgTotalHemoglobinConc", "uint16", 100, 0) },
                { 85, new Field("minTotalHemoglobinConc", "uint16", 100, 0) },
                { 86, new Field("maxTotalHemoglobinConc", "uint16", 100, 0) },
                { 87, new Field("avgSaturatedHemoglobinPercent", "uint16", 10, 0) },
                { 88, new Field("minSaturatedHemoglobinPercent", "uint16", 10, 0) },
                { 89, new Field("maxSaturatedHemoglobinPercent", "uint16", 10, 0) },
                { 91, new Field("avgLeftTorqueEffectiveness", "uint8", 2, 0) },
                { 92, new Field("avgRightTorqueEffectiveness", "uint8", 2, 0) },
                { 93, new Field("avgLeftPedalSmoothness", "uint8", 2, 0) },
                { 94, new Field("avgRightPedalSmoothness", "uint8", 2, 0) },
                { 95, new Field("avgCombinedPedalSmoothness", "uint8", 2, 0) },
                { 96, new Field("numFrontGearChanges", "uint16", 0, 0) },
                { 97, new Field("numRearGearChanges", "uint16", 0, 0) },
                { 98, new Field("timeStanding", "uint32", 1000, 0) },
                { 99, new Field("standCount", "uint16", 0, 0) },
                { 100, new Field("avgLeftPco", "sint8", 0, 0) },
                { 101, new Field("avgRightPco", "sint8", 0, 0) },
                { 102, new Field("avgLeftPowerPhase", "uint8", 0.7111111, 0) },
                { 103, new Field("avgLeftPowerPhasePeak", "uint8", 0.7111111, 0) },
                { 104, new Field("avgRightPowerPhase", "uint8", 0.7111111, 0) },
                { 105, new Field("avgRightPowerPhasePeak", "uint8", 0.7111111, 0) },
                { 106, new Field("avgPowerPosition", "uint16", 0, 0) },
                { 107, new Field("maxPowerPosition", "uint16", 0, 0) },
                { 108, new Field("avgCadencePosition", "uint8", 0, 0) },
                { 109, new Field("maxCadencePosition", "uint8", 0, 0) },
                { 110, new Field("enhancedAvgSpeed", "uint32", 1000, 0) },
                { 111, new Field("enhancedMaxSpeed", "uint32", 1000, 0) },
                { 112, new Field("enhancedAvgAltitude", "uint32", 5, 500) },
                { 113, new Field("enhancedMinAltitude", "uint32", 5, 500) },
                { 114, new Field("enhancedMaxAltitude", "uint32", 5, 500) },
                { 115, new Field("avgLevMotorPower", "uint16", 0, 0) },
                { 116, new Field("maxLevMotorPower", "uint16", 0, 0) },
                { 117, new Field("levBatteryConsumption", "uint8", 2, 0) }
              }
            },
            { 20, new Dictionary<ushort, Field>()
              {
                { 253, new Field("timestamp", "dateTime", 0, 0) },
                { 0, new Field("positionLat", "coordinates", 0, 0) },
                { 1, new Field("positionLong", "coordinates", 0, 0) },
                { 2, new Field("altitude", "uint16", 5, 500) },
                { 3, new Field("heartRate", "uint8", 0, 0) },
                { 4, new Field("cadence", "uint8", 0, 0) },
                { 5, new Field("distance", "uint32", 100, 0) },
                { 6, new Field("speed", "uint16", 1000, 0) },
                { 7, new Field("power", "uint16", 0, 0) },
                { 8, new Field("compressedSpeedDistance", "byte", 100, 0) },
                { 9, new Field("grade", "sint16", 100, 0) },
                { 10, new Field("resistance", "uint8", 0, 0) },
                { 11, new Field("timeFromCourse", "sint32", 1000, 0) },
                { 12, new Field("cycleLength", "uint8", 100, 0) },
                { 13, new Field("temperature", "sint8", 0, 0) },
                { 17, new Field("speed1s", "uint8", 16, 0) },
                { 18, new Field("cycles", "uint8", 0, 0) },
                { 19, new Field("totalCycles", "uint32", 0, 0) },
                { 28, new Field("compressedAccumulatedPower", "uint16", 0, 0) },
                { 29, new Field("accumulatedPower", "uint32", 0, 0) },
                { 30, new Field("leftRightBalance", "leftRightBalance", 0, 0) },
                { 31, new Field("gpsAccuracy", "uint8", 0, 0) },
                { 32, new Field("verticalSpeed", "sint16", 1000, 0) },
                { 33, new Field("calories", "uint16", 0, 0) },
                { 39, new Field("verticalOscillation", "uint16", 10, 0) },
                { 40, new Field("stanceTimePercent", "uint16", 100, 0) },
                { 41, new Field("stanceTime", "uint16", 10, 0) },
                { 42, new Field("activityType", "activityType", 0, 0) },
                { 43, new Field("leftTorqueEffectiveness", "uint8", 2, 0) },
                { 44, new Field("rightTorqueEffectiveness", "uint8", 2, 0) },
                { 45, new Field("leftPedalSmoothness", "uint8", 2, 0) },
                { 46, new Field("rightPedalSmoothness", "uint8", 2, 0) },
                { 47, new Field("combinedPedalSmoothness", "uint8", 2, 0) },
                { 48, new Field("time128", "uint8", 128, 0) },
                { 49, new Field("strokeType", "strokeType", 0, 0) },
                { 50, new Field("zone", "uint8", 0, 0) },
                { 51, new Field("ballSpeed", "uint16", 100, 0) },
                { 52, new Field("cadence256", "uint16", 256, 0) },
                { 53, new Field("fractionalCadence", "uint8", 128, 0) },
                { 54, new Field("totalHemoglobinConc", "uint16", 100, 0) },
                { 55, new Field("totalHemoglobinConcMin", "uint16", 100, 0) },
                { 56, new Field("totalHemoglobinConcMax", "uint16", 100, 0) },
                { 57, new Field("saturatedHemoglobinPercent", "uint16", 10, 0) },
                { 58, new Field("saturatedHemoglobinPercentMin", "uint16", 10, 0) },
                { 59, new Field("saturatedHemoglobinPercentMax", "uint16", 10, 0) },
                { 62, new Field("deviceIndex", "deviceIndex", 0, 0) },
                { 67, new Field("leftPco", "sint8", 0, 0) },
                { 68, new Field("rightPco", "sint8", 0, 0) },
                { 69, new Field("leftPowerPhase", "uint8", 0.7111111, 0) },
                { 70, new Field("leftPowerPhasePeak", "uint8", 0.7111111, 0) },
                { 71, new Field("rightPowerPhase", "uint8", 0.7111111, 0) },
                { 72, new Field("rightPowerPhasePeak", "uint8", 0.7111111, 0) },
                { 73, new Field("enhancedSpeed", "uint32", 1000, 0) },
                { 78, new Field("enhancedAltitude", "uint32", 5, 500) },
                { 81, new Field("batterySoc", "uint8", 2, 0) },
                { 82, new Field("motorPower", "uint16", 0, 0) }
              }
            },
            { 21, new Dictionary<ushort, Field>()
              {
                { 253, new Field("timestamp", "dateTime", 0, 0) },
                { 0, new Field("event", "enumEvent", 0, 0) },
                { 1, new Field("eventType", "enumEventType", 0, 0) },
                { 2, new Field("data16", "uint16", 0, 0) },
                { 3, new Field("data", "uint32", 0, 0) },
                { 4, new Field("eventGroup", "uint8", 0, 0) },
                { 7, new Field("score", "uint16", 0, 0) },
                { 8, new Field("opponentScore", "uint16", 0, 0) },
                { 9, new Field("frontGearNum", "uint8z", 0, 0) },
                { 10, new Field("frontGear", "uint8z", 0, 0) },
                { 11, new Field("rearGearNum", "uint8z", 0, 0) },
                { 12, new Field("rearGear", "uint8z", 0, 0) },
                { 13, new Field("deviceIndex", "raw", 0, 0) }
              }
            },
            { 22, new Dictionary<ushort, Field>()
              {
                { 253, new Field("timestamp", "dateTime", 0, 0) },
                { 0, new Field("speed", "deviceIndex", 0, 0) },
                { 1, new Field("distance", "deviceIndex", 0, 0) },
                { 2, new Field("cadence", "deviceIndex", 0, 0) },
                { 3, new Field("altitude", "deviceIndex", 0, 0) },
                { 4, new Field("heart", "deviceIndex", 0, 0) }
              }
            },
            { 23, new Dictionary<ushort, Field>()
              {
                { 253, new Field("timestamp", "dateTime", 0, 0) },
                { 0, new Field("deviceIndex", "deviceIndex", 0, 0) },
                { 1, new Field("deviceType", "uint8", 0, 0) },
                { 2, new Field("manufacturer", "enumManufacturer", 0, 0) },
                { 3, new Field("serialNumber", "uint32z", 0, 0) },
                { 4, new Field("product", "uint16", 0, 0) },
                { 5, new Field("softwareVersion", "uint16", 100, 0) },
                { 6, new Field("hardwareVersion", "uint8", 0, 0) },
                { 7, new Field("cumOperatingTime", "uint32", 0, 0) },
                { 10, new Field("batteryVoltage", "uint16", 256, 0) },
                { 11, new Field("batteryStatus", "enumBatteryStatus", 0, 0) },
                { 18, new Field("sensorPosition", "enumBodyLocation", 0, 0) },
                { 19, new Field("descriptor", "string", 0, 0) },
                { 20, new Field("antTransmissionType", "uint8z", 0, 0) },
                { 21, new Field("antDeviceNumber", "uint16z", 0, 0) },
                { 22, new Field("antNetwork", "enumAntNetwork", 0, 0) },
                { 23, new Field("serialNumber", "raw", 0, 0) },
                { 24, new Field("sensorSerialNumber", "raw", 0, 0) },
                { 25, new Field("sourceType", "enumSourceType", 0, 0) },
                { 27, new Field("productName", "string", 0, 0) }
              }
            },
            { 34, new Dictionary<ushort, Field>()
              {
                { 253, new Field("timestamp", "dateTime", 0, 0) },
                { 0, new Field("totalTimerTime", "uint32", 0, 0) },
                { 1, new Field("numSessions", "uint16", 0, 0) },
                { 2, new Field("type", "enumActivity", 0, 0) },
                { 3, new Field("event", "enumEvent", 0, 0) },
                { 4, new Field("eventType", "enumEventType", 0, 0) },
                { 5, new Field("localTimestamp", "localDateTime", 0, 0) },
                { 6, new Field("eventGroup", "uint8", 0, 0) }
              }
            },
            { 49, new Dictionary<ushort, Field>()
              {
                { 0, new Field("softwareVersion", "uint16", 0, 0) },
                { 1, new Field("hardwareVersion", "uint8", 0, 0) }
              }
            },
            { 72,  new Dictionary<ushort, Field>()
              {
                { 253, new Field("timestamp", "dateTime", 0, 0) },
                { 0, new Field("type", "enumFile", 0, 0) },
                { 1, new Field("manufacturer", "enumManufacturer", 0, 0) },
                { 2, new Field("product", "uint16", 0, 0) },
                { 3, new Field("serialNumber", "uint32z", 0, 0) },
                { 4, new Field("timeCreated", "dateTime", 0, 0) }
              }
            },
            { 101, new Dictionary<ushort, Field>()
              {
                { 254, new Field("messageIndex", "messageIndex", 0, 0) },
                { 253, new Field("timestamp", "dateTime", 0, 0) },
                { 0, new Field("event", "enumEvent", 0, 0) },
                { 1, new Field("eventType", "enumEventType", 0, 0) },
                { 2, new Field("startTime", "dateTime", 0, 0) },
                { 3, new Field("totalElapsedTime", "uint32", 1000, 0) },
                { 4, new Field("totalTimerTime", "uint32", 1000, 0) },
                { 5, new Field("totalStrokes", "uint16", 0, 0) },
                { 6, new Field("avgSpeed", "uint16", 1000, 0) },
                { 7, new Field("swimStroke", "enumSwimStroke", 0, 0) },
                { 9, new Field("avgSwimmingCadence", "uint8", 0, 0) },
                { 10, new Field("eventGroup", "unit8", 0, 0) },
                { 11, new Field("totalCalories", "uint16", 0, 0) },
                { 12, new Field("lengthType", "enumLengthType", 0, 0) },
                { 18, new Field("playerScore", "uint16", 0, 0) },
                { 19, new Field("opponentScore", "uint16", 0, 0) },
                { 20, new Field("strokeCount", "uint16", 0, 0) },
                { 21, new Field("zoneCount", "uint16", 0, 0) }
              }
            },
            { 104, new Dictionary<ushort, Field>()
              {
                { 253, new Field("timestamp", "dateTime", 0, 0) },
                { 0, new Field("charge", "raw", 0, 0) },
                { 2, new Field("percent", "raw", 0, 0) }
              }
            },
            { 142, new Dictionary<ushort, Field>()
              {
                { 254, new Field("messageIndex", "messageIndex", 0, 0) },
                { 253, new Field("timestamp", "dateTime", 0, 0) },
                { 0, new Field("event", "event", 0, 0) },
                { 1, new Field("eventType", "eventType", 0, 0) },
                { 2, new Field("startTime", "dateTime", 0, 0) },
                { 3, new Field("startPositionLat", "coordinates", 0, 0) },
                { 4, new Field("startPositionLong", "coordinates", 0, 0) },
                { 5, new Field("endPositionLat", "coordinates", 0, 0) },
                { 6, new Field("endPositionLong", "coordinates", 0, 0) },
                { 7, new Field("totalElapsedTime", "uint32", 1000, 0) },
                { 8, new Field("totalTimerTime", "uint32", 1000, 0) },
                { 9, new Field("totalDistance", "uint32", 100, 0) },
                { 10, new Field("totalCycles", "uint32", 0, 0) },
                { 11, new Field("totalCalories", "uint16", 0, 0) },
                { 12, new Field("totalFatCalories", "uint16", 0, 0) },
                { 13, new Field("avgSpeed", "uint16", 1000, 0) },
                { 14, new Field("maxSpeed", "uint16", 1000, 0) },
                { 15, new Field("avgHeartRate", "uint8", 0, 0) },
                { 16, new Field("maxHeartRate", "uint8", 0, 0) },
                { 17, new Field("avgCadence", "uint8", 0, 0) },
                { 18, new Field("maxCadence", "uint8", 0, 0) },
                { 19, new Field("avgPower", "uint16", 0, 0) },
                { 20, new Field("maxPower", "uint16", 0, 0) },
                { 21, new Field("totalAscent", "uint16", 0, 0) },
                { 22, new Field("totalDescent", "uint16", 0, 0) },
                { 23, new Field("sport", "sport", 0, 0) },
                { 24, new Field("eventGroup", "uint8", 0, 0) },
                { 25, new Field("necLat", "coordinates", 0, 0) },
                { 26, new Field("necLong", "coordinates", 0, 0) },
                { 27, new Field("swcLat", "coordinates", 0, 0) },
                { 28, new Field("swcLong", "coordinates", 0, 0) },
                { 29, new Field("name", "string", 0, 0) },
                { 30, new Field("normalizedPower", "uint16", 0, 0) },
                { 31, new Field("leftRightBalance", "leftRightBalance100", 0, 0) },
                { 32, new Field("subSport", "subSport", 0, 0) },
                { 33, new Field("totalWork", "uint32", 0, 0) },
                { 34, new Field("avgAltitude", "uint16", 5, 500) },
                { 35, new Field("maxAltitude", "uint16", 5, 500) },
                { 36, new Field("gpsAccuracy", "uint8", 0, 0) },
                { 37, new Field("avgGrade", "sint16", 100, 0) },
                { 38, new Field("avgPosGrade", "sint16", 100, 0) },
                { 39, new Field("avgNegGrade", "sint16", 100, 0) },
                { 40, new Field("maxPosGrade", "sint16", 100, 0) },
                { 41, new Field("maxNegGrade", "sint16", 100, 0) },
                { 42, new Field("avgTemperature", "sint8", 0, 0) },
                { 43, new Field("maxTemperature", "sint8", 0, 0) },
                { 44, new Field("totalMovingTime", "uint32", 1000, 0) },
                { 45, new Field("avgPosVerticalSpeed", "sint16", 1000, 0) },
                { 46, new Field("avgNegVerticalSpeed", "sint16", 1000, 0) },
                { 47, new Field("maxPosVerticalSpeed", "sint16", 1000, 0) },
                { 48, new Field("maxNegVerticalSpeed", "sint16", 1000, 0) },
                { 49, new Field("timeInHrZone", "uint32", 1000, 0) },
                { 50, new Field("timeInSpeedZone", "uint32", 1000, 0) },
                { 51, new Field("timeInCadenceZone", "uint32", 1000, 0) },
                { 52, new Field("timeInPowerZone", "uint32", 1000, 0) },
                { 53, new Field("repetitionNum", "uint16", 0, 0) },
                { 54, new Field("minAltitude", "uint16", 5, 0) },
                { 55, new Field("minHeartRate", "uint8", 0, 0) },
                { 56, new Field("activeTime", "uint32", 1000, 0) },
                { 57, new Field("wktStepIndex", "messageIndex", 0, 0) },
                { 58, new Field("sportEvent", "sportEvent", 0, 0) },
                { 59, new Field("avgLeftTorqueEffectiveness", "uint8", 2, 0) },
                { 60, new Field("avgRightTorqueEffectiveness", "uint8", 2, 0) },
                { 61, new Field("avgLeftPedalSmoothness", "uint8", 2, 0) },
                { 62, new Field("avgRightPedalSmoothness", "uint8", 2, 0) },
                { 63, new Field("avgCombinedPedalSmoothness", "uint8", 2, 0) },
                { 64, new Field("status", "segmentLapStatus", 0, 0) },
                { 65, new Field("uuid", "string", 0, 0) },
                { 66, new Field("avgFractionalCadence", "uint8", 128, 0) },
                { 67, new Field("maxFractionalCadence", "uint8", 128, 0) },
                { 68, new Field("totalFractionalCycles", "uint8", 128, 0) },
                { 69, new Field("frontGearShiftCount", "uint16", 0, 0) },
                { 70, new Field("rearGearShiftCount", "uint16", 0, 0) },
                { 71, new Field("timeStanding", "uint32", 1000, 0) },
                { 72, new Field("standCount", "uint16", 0, 0) },
                { 73, new Field("avgLeftPco", "sint8", 0, 0) },
                { 74, new Field("avgRightPco", "sint8", 0, 0) },
                { 75, new Field("avgLeftPowerPhase", "uint8", 0.7111111, 0) },
                { 76, new Field("avgLeftPowerPhasePeak", "uint8", 0.7111111, 0) },
                { 77, new Field("avgRightPowerPhase", "uint8", 0.7111111, 0) },
                { 78, new Field("avgRightPowerPhasePeak", "uint8", 0.7111111, 0) },
                { 79, new Field("avgPowerPosition", "uint16", 0, 0) },
                { 80, new Field("maxPowerPosition", "uint16", 0, 0) },
                { 81, new Field("avgCadencePosition", "uint8", 0, 0) },
                { 82, new Field("maxCadencePosition", "uint8", 0, 0) }
              }
            },
            { 147, new Dictionary<ushort, Field>()
              {
                { 0, new Field("serialNumber", "raw", 0, 0) },
                { 2, new Field("name", "raw", 0, 0) },
                { 17, new Field("numFrontGears", "raw", 0, 0) },
                { 18, new Field("frontGears", "raw", 0, 0) },
                { 19, new Field("numBackGears", "raw", 0, 0) },
                { 20, new Field("backGears", "raw", 0, 0) },
                { 32, new Field("product", "raw", 0, 0) },
                { 34, new Field("softwareVersion", "raw", 0, 0) },
                { 254, new Field("messageIndex", "messageIndex", 0, 0) },
              }
            }
        };

        internal static Dictionary<ushort, Dictionary<ushort, Field>> _Fields { get => fields; }
    }
}